				<div id="masonry-bloc">
					<div>
				    	<div class="bloc">
				    		<img id="img" src="./img/item.jpg" alt="" width="350" height="400" />
				    	</div>
				    	<div class="bloc">
				    		<img id="img" src="./img/item.jpg" alt="" width="350" height="400" />
				    	</div>
				    	<div class="bloc">
				    		<img id="img" src="./img/item.jpg" alt="" width="350" height="400" />
				    	</div>
			    	</div>
			    	<div>
				    	<div class="banner bloc">
				    		<img id="img" src="./img/item.jpg" alt="" width="1070" height="400" />
				    	</div>
			    	</div>
			    	<div>
				    	<div class="bloc">
				    		<img id="img" src="./img/item.jpg" alt="" width="350" height="300" />
				    	</div>
				    	<div class="bloc">
				    		<img id="img" src="./img/item.jpg" alt="" width="350" height="300" />
				    	</div>
				    	<div class="bloc">
				    		<img id="img" src="./img/item.jpg" alt="" width="350" height="300" />
				    	</div>
			    	</div>
			    </div>
		    </div>