<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <title>Site test</title>
        <link rel="icon" type="image/png" href="img/favicon.png" />
		<meta name="description" content="Envirennement de test">
        <meta name="viewport" content="width=device-width" />

        <link rel="stylesheet" href="css/main.css" />
        <script type="text/javascript" src="js/vendor/jquery-2.0.3.js"></script>
        <script type="text/javascript" src="js/plugins.js"></script>
        <script type="text/javascript" src="js/main.js"></script>
    </head>
    <body>
    	<div id="container">
    	<!-- ===================================== HEADER ====================================================== -->
	        <div id="header-default">
		        <div class="header-content">
		        	<div id="Slider1" class="slider_container">
						<div class="slider">
							<a href="#" style="background: url('./img/slide1.jpg') center no-repeat;"></a>
							<a href="#" style="background: url('./img/slide2.jpg') center no-repeat;"></a>
							<a href="#" style="background: url('./img/slide3.jpg') center no-repeat;"></a>
						</div>
						<div class="slider-caption">
							<h1>Ü</h1>
							<div class="slider-line"></div>
							<h2>Deux points sur le ü</h2>
							<div class="slider-line"></div>
							<ul class="links">
								<li><a href="#"><img src="" alt="facebook" /></a><li>
								<li><a href="#"><img src="" alt="pinterest" /></a></li>
							</ul>
						</div>
						<div class="prev"></div>
						<div class="next"></div>
						<div class="steps">
							<ul class="puces">
							</ul>
						</div>
					</div>
		        	<div class="header-title"><h1>Deux points sur le ü</h1></div>
			        <div class="header-nav">
						<ul>
							<li><a href="/category" class="nav-cat">Catégories</a></li>
							<li><a href="/about">Ã propos</a></li>
						</ul>
						<ul class="right">
							<li>
								<ul class="links">
									<li><a href="#"><img src="" alt="facebook" /></a><li>
									<li><a href="#"><img src="" alt="pinterest" /></a></li>
								</ul>
							</li>
							<li><a class="btn-dawanda" href="#">Retrouvez ma boutique sur Dawanda</a></li>
						</ul>
				    </div>
				</div>
			    <div class="navbar-popup">
			       	<ul>
			    		<li><a href="#tous" class="tous">Tous</a></li>
				   		<li><a href="#bijoux" class="cats">Bijoux</a></li>
				   		<li><a href="#objet" class="cats">Objet</a></li>
				   		<li><a href="#papeterie" class="cats">Papéterie</a></li>
			    	</ul>
				</div>
	   		</div>
	   		
	   		<div id="header-fixed">
	   			<div class="header-content">	
	        		<div class="header-title"><h1>Deux points sur le ü</h1></div>
		        	<div class="header-nav">
						<ul>
							<li><a class="nav-cat">Catégories</a></li>
							<li><a href="#">Ã propos</a></li>
						</ul>
						<ul class="right">
							<li><a href="#"><img src="" alt="facebook" /></a></li>
							<li><a href="#"><img src="" alt="pinterest" /></a></li>
							<li><a class="btn-dawanda" href="#">Retrouvez ma boutique sur Dawanda</a></li>
						</ul>
			    	</div>
			    </div>
			    <div class="navbar-popup">
			       	<ul>
			    		<li><a href="#tous" class="tous">Tous</a></li>
				   		<li><a href="#bijoux" class="cats">Bijoux</a></li>
				   		<li><a href="#objet" class="cats">Objet</a></li>
				   		<li><a href="#papeterie" class="cats">Papéterie</a></li>
			    	</ul>
			    </div>
			</div>
			<!-- ===================================== CONTENT ===================================================== -->
		    
		    <?php echo $page; ?>
		    
		    <!-- ===================================== FOOTER ====================================================== -->	
		    <div id="footer">
		    	<div id="barre"></div>
		    	<div id="footer-menu">
		    		<ul>
		    			<li>Deux points sur le U - 2013</li>
		    			<li class="right">
		    				<ul>
		    					<li><a href="#">A propos</a></li>
		    					<li><a href="#">Contact</a></li>
		    				</ul>
		    			</li>
		    		</ul>
		    	</div>
		    </div>
		    
    	</div>
    </body>
</html>